apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubectl
  labels:
    app: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubectl
  template:
    metadata:
      labels:
        app: kubectl
    spec:
      serviceAccountName: kubectl
      containers:
        - name: kubectl
          image: bitnami/kubectl:1.19.12
          command:
            - sleep
            - "100000"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubectl
  name: kubectl
spec:
  ports:
  - port: 25000
    protocol: TCP
    targetPort: 25000
  selector:
    app: kubectl
  type: ClusterIP

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubectl
  namespace: zadig-env-27149chen

